export const components = {
  Accordion: 0,
  Avatar: 1,
  Badge: 2,
  "Bottom navigation": 3,
  Breadcrumbs: 4,
  Button: 5,
  "Button group": 6,
  "Button pre-defined styles": 7,
  "Button sizes": 8,
  "Button with icons": 9,
  Calendar: 10,
  Card: 11,
  Carousel: 12,
  Cascader: 13,
  Checkbox: 14,
  "Chip/Tag": 15,
  Comment: 16,
  "Date picker": 17,
  "Datetime picker": 18,
  Divider: 19,
  Drawer: 20,
  Grid: 21,
  "Icon button": 22,
  Icons: 23,
  "Input with color": 24,
  "Input with error": 25,
  "Input with prefix": 26,
  "Input with suffix": 27,
  Layout: 28,
  Link: 29,
  List: 30,
  Menu: 31,
  Modal: 32,
  "Multiline input": 33,
  "Number input": 34,
  Pagination: 35,
  Popconfirm: 36,
  Popover: 37,
  "Progress circular": 38,
  "Progress linear": 39,
  Radio: 40,
  Rating: 41,
  Select: 42,
  Skeleton: 43,
  Slider: 44,
  "Snackbar/Alert": 45,
  Statistic: 46,
  Stepper: 47,
  "Sticky button": 48,
  Switch: 49,
  Table: 50,
  Tabs: 51,
  "Text input": 52,
  "Time picker": 53,
  Timeline: 54,
  Tooltip: 55,
  "Top bar": 56,
  Transferlist: 57,
  Tree: 58,
  "Upload button": 69,
};

export const frameworks: any = {
  "Material UI": {
    name: "Material UI",
    components: {
      Accordion: 1,
      Avatar: 1,
      Badge: 1,
      "Bottom navigation": 1,
      Breadcrumbs: 1,
      Button: 1,
      "Button group": 1,
      "Button pre-defined styles": 1,
      "Button sizes": 1,
      "Button with icons": 1,
      Card: 1,
      Checkbox: 1,
      "Chip/Tag": 1,
      "Date picker": 1,
      "Datetime picker": 1,
      Divider: 1,
      Drawer: 1,
      Grid: 1,
      "Icon button": 1,
      Icons: 1,
      "Input with color": 1,
      "Input with error": 1,
      "Input with prefix": 1,
      "Input with suffix": 1,
      Layout: 1,
      Link: 1,
      List: 1,
      Menu: 1,
      Modal: 1,
      "Multiline input": 1,
      "Number input": 1,
      "Progress circular": 1,
      "Progress linear": 1,
      Radio: 1,
      Select: 1,
      Slider: 1,
      "Snackbar/Alert": 1,
      Stepper: 1,
      "Sticky button": 1,
      Switch: 1,
      Table: 1,
      Tabs: 1,
      "Text input": 1,
      "Time picker": 1,
      Tooltip: 1,
      "Top bar": 1,
    },
  },
  "Ant Design": {
    name: "Ant Design",
    components: {
      Accordion: 1,
      Avatar: 1,
      Badge: 1,
      Breadcrumbs: 1,
      Button: 1,
      "Button pre-defined styles": 1,
      "Button sizes": 1,
      "Button with icons": 1,
      Calendar: 1,
      Card: 1,
      Carousel: 1,
      Cascader: 1,
      Checkbox: 1,
      "Chip/Tag": 1,
      Comment: 1,
      "Date picker": 1,
      "Datetime picker": 1,
      Divider: 1,
      Drawer: 1,
      Grid: 1,
      "Icon button": 1,
      Icons: 1,
      "Input with color": 1,
      "Input with error": 1,
      "Input with prefix": 1,
      "Input with suffix": 1,
      Layout: 1,
      List: 1,
      Menu: 1,
      Modal: 1,
      "Multiline input": 1,
      "Number input": 1,
      Pagination: 1,
      Popconfirm: 1,
      Popover: 1,
      "Progress circular": 1,
      "Progress linear": 1,
      Radio: 1,
      Rating: 1,
      Select: 1,
      Skeleton: 1,
      Slider: 1,
      "Snackbar/Alert": 1,
      Statistic: 1,
      Stepper: 1,
      "Sticky button": 1,
      Switch: 1,
      Table: 1,
      Tabs: 1,
      "Text input": 1,
      "Time picker": 1,
      Timeline: 1,
      Tooltip: 1,
      "Top bar": 1,
      Transferlist: 1,
      Tree: 1,
      "Upload button": 1,
    },
  },
  Reakit: {
    name: "Reakit",
    components: {
      Button: 1,
      "Button group": 1,
      Checkbox: 1,
      Divider: 1,
      Menu: 1,
      Modal: 1,
      Radio: 1,
      Tabs: 1,
      "Text input": 1,
      Tooltip: 1,
      "Top bar": 1,
    },
  },
  "Chakra UI": {
    name: "Chakra UI",
    components: {
      Accordion: 1,
      Avatar: 1,
      Badge: 1,
      Breadcrumbs: 1,
      Button: 1,
      "Button group": 1,
      "Button pre-defined styles": 1,
      "Button sizes": 1,
      "Button with icons": 1,
      Checkbox: 1,
      "Chip/Tag": 1,
      Divider: 1,
      Drawer: 1,
      Grid: 1,
      "Icon button": 1,
      Icons: 1,
      "Input with color": 1,
      "Input with error": 1,
      "Input with prefix": 1,
      "Input with suffix": 1,
      Layout: 1,
      List: 1,
      Link: 1,
      Menu: 1,
      Modal: 1,
      "Multiline input": 1,
      "Number input": 1,
      Popconfirm: 1,
      "Progress circular": 1,
      "Progress linear": 1,
      Radio: 1,
      Select: 1,
      Skeleton: 1,
      Slider: 1,
      "Snackbar/Alert": 1,
      Statistic: 1,
      Switch: 1,
      Table: 1,
      Tabs: 1,
      "Text input": 1,
      Tooltip: 1,
    },
  },
};
